begin;
select plan(21);
select has_table('public','ai_providers','provider registry exists');
select has_table('public','ai_models','model registry exists');
select has_table('public','ai_prompt_templates','prompt templates exist');
select has_table('public','ai_prompt_versions','prompt versions exist');
select has_table('public','ai_guardrails','guardrails exist');
select has_table('public','ai_conversations','conversations exist');
select has_table('public','ai_usage_events','usage evidence exists');
select has_table('public','ai_embeddings_registry','disabled embeddings registry exists');
select has_view('public','ai_provider_catalog_projection','provider projection exists');
select has_view('public','ai_usage_summary_projection','usage projection exists');
select has_view('public','reporting_ai_metrics','reporting projection exists');
select has_function('public','register_ai_provider',array['uuid','text','text','text','jsonb'],'provider RPC exists');
select has_function('public','create_ai_workflow',array['uuid','uuid','text','text','boolean'],'workflow RPC exists');
select has_function('public','create_ai_conversation',array['uuid','text','integer'],'conversation RPC exists');
select ok((select relforcerowsecurity from pg_class where oid='public.ai_providers'::regclass),'provider registry forces RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.ai_conversations'::regclass),'conversations force RLS');
select ok(not exists(select 1 from pg_policies where schemaname='public' and tablename like 'ai_%' and 'anon'=any(roles)),'no anonymous AI policies exist');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name like 'ai_%' and column_name ~ '(api_key|client_secret|access_token|credential)'),'no credential columns exist');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name='ai_embeddings_registry' and udt_name='vector'),'embeddings registry stores no vectors');
select has_trigger('public','ai_prompt_versions','ai_prompt_versions_published_immutable');
select has_trigger('public','ai_usage_events','ai_usage_events_immutable');
select * from finish();
rollback;
