begin;
select plan(22);
select has_table('public','ai_execution_policies','execution policy exists');
select has_table('public','ai_provider_health','provider health exists');
select has_table('public','ai_provider_circuit_states','circuit state exists');
select has_table('public','ai_model_routes','model routes exist');
select has_table('public','ai_provider_fallback_rules','fallback rules exist');
select has_table('public','ai_provider_kill_switches','kill switches exist');
select has_table('public','ai_cost_rates','cost rates exist');
select has_table('public','ai_execution_requests','execution requests exist');
select has_table('public','ai_budget_reservations','budget reservations exist');
select has_table('public','ai_execution_attempts','attempt evidence exists');
select has_table('public','ai_execution_results','result evidence exists');
select has_table('public','ai_execution_failures','failure evidence exists');
select has_table('public','ai_execution_redactions','redaction evidence exists');
select has_table('public','ai_execution_policy_decisions','policy evidence exists');
select has_view('public','ai_execution_audit_projection','audit projection exists');
select has_view('public','reporting_ai_execution_metrics','reporting projection exists');
select has_function('public','begin_ai_execution',array['uuid','uuid','uuid','text','uuid','text','text','text','text','uuid','uuid','integer','integer','integer','text','timestamp with time zone'],'controlled execution RPC exists');
select has_function('public','complete_ai_execution',array['uuid','uuid','uuid','uuid','text','text','text','integer','integer','integer','integer','bigint','text','text','text[]','integer'],'controlled completion RPC exists');
select ok((select bool_and(relforcerowsecurity) from pg_class where oid in ('public.ai_execution_requests'::regclass,'public.ai_execution_results'::regclass,'public.ai_execution_failures'::regclass)),'execution evidence forces RLS');
select ok(not exists(select 1 from pg_policies where schemaname='public' and tablename like 'ai_%' and 'anon'=any(roles)),'no anonymous AI policies exist');
select ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name like 'ai_%' and column_name ~ '(api_key|client_secret|access_token|credential|prompt_text|output_text|message_content)'),'no secrets or plaintext execution content exist');
select has_trigger('public','ai_execution_results','ai_execution_results_immutable');
select * from finish();
rollback;
