begin;
select plan(15);
select has_table('public','community_spaces','Community spaces exist');
select has_table('public','discussion_posts','Discussion posts exist');
select has_table('public','chat_messages','Chat messages exist');
select has_table('public','live_sessions','Live sessions exist');
select has_table('public','live_session_attendance','Attendance evidence exists');
select has_table('public','office_hour_bookings','Office-hour bookings exist');
select has_table('public','study_groups','Study groups exist');
select has_table('public','whiteboard_versions','Whiteboard versions exist');
select has_view('public','community_dashboard_projection','Community projection exists');
select has_view('public','reporting_community_projection','Reporting projection exists');
select has_function('public','create_discussion',array['uuid','uuid','text','text'],'Discussion creation is controlled');
select has_function('public','send_message',array['uuid','text','uuid','jsonb'],'Messaging is controlled');
select has_function('public','record_attendance',array['uuid','uuid','timestamptz','timestamptz','text','text'],'Attendance is controlled');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.chat_messages'::regclass),'Chat forces RLS');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.communication_events'::regclass),'Communication events force RLS');
select * from finish();
rollback;
